### ISSUE TITLE
Help on building and using?

### ISSUE THREAD

**Issue by neilbacon** [georgesolomos/enket#2]
This looks useful, but how do I build and use it? Could you add this to the `README` please?

I have `go version go1.21.3 linux/amd64`

    go build 
    package github.com/georgesolomos/enket: build constraints exclude all Go files in /home/neil/sw/enket

How do I fix this?

I just did this project: https://github.com/neilbacon/elec
before learning how to search README's in GitHub and finding your more comprehensive version!

**Comment by georgesolomos** [comment]
Hi Neil. I started this as a personal project and it's been slow going lately with a lot of other things happening in my life.

From the root, you can just run it using `go run cmd/enketcli/main.go -nem12path="file.csv"`.

The `main.go` file is very much a WIP with some stuff hardcoded, commented out, etc. The NEM12 parsing is complete but the price calculation is only about 10% done.
